### ISSUE TITLE
Issues while deploying a release game

### ISSUE THREAD

**Issue by fgnm** [Berstanio/MetalANGLEKit#2]
There are couple issues I found while deploying the framework bundled in a libGDX game using RoboVM.

- The three frameworks built by ANGLE (libEGL, libfeature_support and libGLESv2) misses the key `CFBundleShortVersionString` in their `Info.plist`. While the framework `MetalANGLEKit` has a correct file.
- Nested frameworks are not friendly. Apple itself discourages to use them, and RoboVM didn't understand them very well. While packing the final IPA, frameworks are put twice: the first one flatted in the `Frameworks` directory and second time in `MetalANGLEKit/Frameworks` subdirectory. This causes duplicate bundle identifiers issues and moreover nested frameworks are not signed properly by RoboVM build scripts.

For both issues solution is however straightforward enough:
- Just add the entry manually with a script if there is no option in ANGLE to produce a right `Info.plist` 
- Flat frameworks so that they are not nested in `MetalANGLEKit`

With both, I was successfully able to upload the IPA fine to Testflight, waiting the approval.

**Comment by Berstanio** [comment]
Fixed both in v1.1
https://github.com/Berstanio/libgdx/tree/feat/use-stock-angle is updated
